### ISSUE TITLE
Consider increasing the recursion limit

### ISSUE THREAD

**Issue by bmp2** [ldeluigi/commander-spellbook-backend#43]

**Comment by ldeluigi** [comment]
why?

**Comment by bmp2** [comment]
Because when the recursion limit is reached the job fails and none of the variants are saved.

**Comment by bmp2** [comment]
If the calculation for a variant exceeds the recursion limit, log it for troubleshooting and move on to the next variant. Failing out the whole job loses a bunch of valid data that will have to be recalculated the next time.

**Comment by ldeluigi** [comment]
> If the calculation for a variant exceeds the recursion limit, log it for troubleshooting and move on to the next variant. Failing out the whole job loses a bunch of valid data that will have to be recalculated the next time.

The current behavior is intended. The problem is that a combo that would cause a recursion limit hit should have never been accepted in the first place. I just submitted an update that should fix the check. If it works, I'll consider increasing the recursion limit based on the specific case you are encountering.

**Comment by ldeluigi** [comment]
Solved. It was caused by a bug.
